apiVersion: v1
kind: Secret
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Release.Namespace}}
  labels:
    app: {{.Chart.Name}}
    heritage: {{.Release.Service}}
    release: {{.Release.Name}}
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
type: opaque
stringData:
  HLAB_POSTGRES_HOST: {{ .Values.secretMap.HLAB_POSTGRES_HOST | quote }}
  HLAB_POSTGRES_PASSWORD: {{ .Values.secretMap.HLAB_POSTGRES_PASSWORD | quote }}
  HLAB_POSTGRES_USER: {{ .Values.secretMap.HLAB_POSTGRES_USER | quote }}
  HLAB_POSTGRES_DB: {{ .Values.secretMap.HLAB_POSTGRES_DB | quote }}




