apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - name: 'http'
      port: 80
      targetPort: {{ .Values.deploymentConfig.containerPort }}
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql
spec:
  type: {{ .Values.postgresql.type }}
  ports:
  - port: {{ .Values.postgresql.service.port }}
    targetPort: {{ .Values.postgresql.service.port }}
  selector:
    app: {{ .Release.Name }}-postgresql
